### ISSUE TITLE
(Bug report) Incorrect thermalization using IME relaxation with zeeman-liouv basis

### ISSUE THREAD

**Issue by FilipVJensen** [IlyaKuprov/Spinach#22]
First of all, thank you for developing Spinach, it has been a great tool for me to learn about spin dynamics.

While I was using your software, I think I might have found a minor mistake in the way the unit_state is calculated for the 'zeeman-liouv' basis.

The problem arose when using relaxation.m which calls thermalize.m to get the relaxation superoperator. I was using the 'IME' relaxation type as shown on image 1 and 2.
<img width="386" alt="1" src="https://github.com/user-attachments/assets/07fe279f-e438-4aac-abd2-9674c47fd84f">
<img width="280" alt="2" src="https://github.com/user-attachments/assets/4056802e-3019-40e2-a2c9-d657240b70ed">

The problem is that after applying the IME correction the relaxation superoperator does not yield zero when applied to the thermal equilibrium, which as far as I understand it should. This can be seen on image 3.
<img width="269" alt="3" src="https://github.com/user-attachments/assets/a1f42d72-6359-4c63-b931-4eb343758638">

I believe the root of the problem is that a normalization is applied to the unit_state, which should be omitted (see image 4).
<img width="355" alt="4" src="https://github.com/user-attachments/assets/3ecf7e0b-e8d9-4d13-97b9-77b01215f60f">

When I do the calculation without this last part, the result is much closer to zero, as seen on image 5.
<img width="357" alt="5" src="https://github.com/user-attachments/assets/423aebad-7f14-492c-9aa5-43c8d6688188">

Of course, I do not know if this is just some mistake I made, but I thought you might want to know about the issue, in case it is something that should be fixed.

Best regards, Filip Vestergaard Jensen

**Comment by IlyaKuprov** [comment]
Thanks - investigating...

**Comment by IlyaKuprov** [comment]
OK, I agree that that particular unit state inside thermalize() should be normalised differently. It cannot be done globally inside unit_state() though because all sorts of observables would then become thermodynamically inconsistent between formalisms, not to mention the fact that the norm of the unit state would depend on the presence of observer spins... thinking about the best way to proceed.

**Comment by IlyaKuprov** [comment]
OK, check the latest commit - should be solved now. I made the thermaliser formalism-specific and also fixed a related bug (see relaxation.m changes) wherein the relaxation superoperator starts damping the unit state in zeeman-liouv formalism in certain circumstances.

**Comment by FilipVJensen** [comment]
Makes sense, thank you very much.

Best regards, Filip
